# Generated by Django 5.2.11 on 2026-03-10 20:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fact_alter_carouselimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='icon',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='facts/'),
        ),
    ]
