# Generated by Django 5.2.11 on 2026-03-10 20:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='testimonials/')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
