# Generated by Django 5.2.11 on 2026-03-11 18:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutheader',
            name='header_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='about/headers/'),
        ),
    ]
