# Generated by Django 5.2.11 on 2026-03-11 18:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutheader_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('experience_years', models.IntegerField()),
                ('image1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='about/')),
                ('image2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='about/')),
            ],
        ),
    ]
