# Generated by Django 5.2.11 on 2026-03-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='pdf',
        ),
        migrations.AddField(
            model_name='catalog',
            name='drive_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
