# Generated by Django 5.2.11 on 2026-03-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_catalog_pdf_catalog_drive_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='catalog_pdfs/'),
        ),
    ]
