# Generated by Django 5.2.11 on 2026-03-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalog_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='catalog',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
