# Generated by Django 5.2.11 on 2026-03-10 20:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_catalog_options_catalog_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='catalog_images/'),
        ),
    ]
